name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install tox, pytest, and dependencies
        run: |
            pip install tox
            pip install pytest
            pip install -r requirements.txt

            # Install any other necessary dependencies
            # pip install package_name
  
      - name: Run black style check
        run: |
            pip install black==23.7.0
            python3 -m black --preview --check .
    
      - name: Run tests
        run: tox
